### ISSUE TITLE
Data objects should be shallow cloned

### ISSUE THREAD

**Issue by Schamper** [benchpressjs/benchpressjs#1]
https://github.com/psychobunny/templates.js/blob/master/lib/templates.js#L76
Right now all the global vars will be appended to the data object. When the parsed template is returned, the data object will contain all these vars.

**Comment by pitaj** [comment]
I'd almost prefer deep cloning for a `sanitize` function. Hell, why not just `JSON.parse(JSON.stringify())` it to do so. Something like this: 

```javascript
function sanitise(obj) {
  return JSON.parse(JSON.stringify(obj));
}
```

This wouldn't work for circular structures, and could be slow, but hell, they shouldn't have too much complexity in the first place.

**Comment by psychobunny** [comment]
The reason why I left this open is because at some point tjs supported automated data binding (so if you clone the object, it would defeat the purpose)

I do plan on bringing it back in the future, so I'll probably not close this I think

**Comment by pitaj** [comment]
Mmmm, okay. That makes more sense.

**Comment by pitaj** [comment]
No longer relevant
