### ISSUE TITLE
2.4.2 breaks pictures in user lists

### ISSUE THREAD

**Issue by barisusakli** [benchpressjs/benchpressjs#106]
```
{{each users}}}
		<li>
			<a href="{config.relative_path}/uid/{../uid}">{buildAvatar(users, "sm", true)} {../username}</a>
		</li>
{{{end}}}
```
works fine on 2.4.1

**Comment by pitaj** [comment]
Please provide sample data, the helper function, and the expected output

Or better yet add a failing test case in a new branch.

**Comment by barisusakli** [comment]
data => https://community.nodebb.org/api/users?pretty=1
template => https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/partials/users_list.tpl
helper => https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/helpers.js#L281

**Comment by pitaj** [comment]
2.4.3
