### ISSUE TITLE
colon is treated as sub property

### ISSUE THREAD

**Issue by barisusakli** [benchpressjs/benchpressjs#33]
Data

```
{
 "users:reputation" :true,
 "users": [{reputation: 0}, {reputation:0}]
}
```

```
<!-- IF users:reputation -->

<!-- ENDIF users:reputation -->
```

The if statement accesses the user array reputation field

**Comment by pitaj** [comment]
So, only a period should signify an object property

**Comment by psychobunny** [comment]
This seems to work, have a look at https://github.com/psychobunny/templates.js/commit/666c827869b4141da0ebaa07951eaf205e8f205f

**Comment by barisusakli** [comment]
Still doesn't work for me on the actual data/template, want me to commit to core and persona?

**Comment by barisusakli** [comment]
Maybe try changing the values in the test to `1` or `"0"` instead of `0`

**Comment by psychobunny** [comment]
If at all possible edit commit above and run npm test and try to break it. Otherwise commit in branch in persona?

**Comment by psychobunny** [comment]
And yeah, I did try messing about with strings, true, false etc, couldn't break it

**Comment by barisusakli** [comment]
Re-open please :rage3:

**Comment by psychobunny** [comment]
Why? This works perfectly :trollface:

![](https://38.media.tumblr.com/tumblr_lrc0ahHnht1qabfx1o1_500.gif)

**Comment by barisusakli** [comment]
:snail:

**Comment by psychobunny** [comment]
Remind me, were you able to make a breaking test for this? All my tests are passing :tm:

**Comment by barisusakli** [comment]
yes just use it in nodebb /users :trollface:

**Comment by psychobunny** [comment]
note to self https://github.com/NodeBB/NodeBB/commit/fba6f3ba8166c9ce106834e890c00cf43847fa9a#diff-ac4dda48eab632d49ff272ffa525a787

**Comment by barisusakli** [comment]
seems to be fixed on benchpress as well
