### ISSUE TITLE
Inner loops

### ISSUE THREAD

**Issue by NicolasSiver** [benchpressjs/benchpressjs#41]
I have tried different compositions, but It just does not work for me. But in the same time, I'm not sure that I'm using Templates.js properly.

For example, where can we use such references? `../something` ? Can it brake inner loops?

Here is an example of sub-categories - https://github.com/NodeBB/nodebb-theme-persona/issues/92#issuecomment-118088218

It looks like, with very first `../`occurrence, it exits inner loop.

**Comment by NicolasSiver** [comment]
Confirming, there is a problem with `../` references, by removing them:

![screen shot 2015-07-07 at 8 29 34 pm](https://cloud.githubusercontent.com/assets/135263/8552645/0a558122-24e7-11e5-8ad4-7d4e01e06b44.png)

@psychobunny do you have recommendation how to reuse same template in several places?

**Comment by psychobunny** [comment]
Yes you're right, ../ goes straight to root. Maybe it should go one loop up at a time, that would make more sense.

Right now though, you can still access the parent loop by using the long form: `{loop1.value}`, I'm pretty sure we use this in a few places in NodeBB itself

ex.

```
<!-- BEGIN loop1 -->
  <!-- BEGIN loop2 -->
    {loop1.value} this should work
  <!-- END loop2 -->
<!-- END loop1 -->
```

**Comment by NicolasSiver** [comment]
Ok, but I would like to reuse templates. Most of them use `../` references. For example link.tpl from categories, so It does not work for me when it is used in: `categories` loop and `categories.children` loop in the same time.

So in current case, I should qualify references like this:

{categories.children.name} or {categories.name}.

> Maybe it should go one loop up at a time

Do you plan to do this change? Because I'm not sure if you will enjoy pull request to the Persona, where only a few templates are reused ;)

**Comment by pitaj** [comment]
Fixed in Benchpress
