### ISSUE TITLE
HTML comments escaped in output

### ISSUE THREAD

**Issue by BenLubar** [benchpressjs/benchpressjs#54]
For example, `<!-- foo -->` turns into `&lt;!-- foo --&gt;` in the output even though other HTML tags are passed through unchanged.

**Comment by codecowboy** [comment]
How do we do block comments?

I tried:
```
{*		<span class="post-tools">
			<a component="post/reply" href="#" class="no-select <!-- IF !privileges.topics:reply -->hidden<!-- ENDIF !privileges.topics:reply -->">[[topic:reply]]</a>
			<a component="post/quote" href="#" class="no-select <!-- IF !privileges.topics:reply -->hidden<!-- ENDIF !privileges.topics:reply -->">[[topic:quote]]</a>
		</span>*}
```

but the curly brace and asterisk are rendered.

**Comment by pitaj** [comment]
you can use regular old HTML comments now as long as they don't start with `IF`, `BEGIN`, or `END`
