### ISSUE TITLE
Import statement in IF statement

### ISSUE THREAD

**Issue by K68** [benchpressjs/benchpressjs#59]
I want to import different partial templates based on IF statement. Maybe a bug here:

```
<!-- IF loggedIn -->
  <!-- IMPORT partials/topics_list.tpl -->
<!-- ELSE -->
  <!-- IMPORT partials/topics_list_diy.tpl -->
<!-- ENDIF loggedIn -->
```

throw error:

> RangeError: Maximum call stack size exceeded
>     at String.match (native)
>     at checkConditional (D:\workspace\NodeBB-1.0.3\node_modules.npminstall\templates.js\0.3.4\templates.js\lib\templates.js:227:26)
>     at checkConditionals (D:\workspace\NodeBB-1.0.3\node_modules.npminstall\templates.js\0.3.4\templates.js\lib\templates.js:223:27)
>     at parseValue (D:\workspace\NodeBB-1.0.3\node_modules.npminstall\templates.js\0.3.4\templates.js\lib\templates.js:389:14)

**Comment by xidui** [comment]
+1
I also met this problem.

**Comment by pitaj** [comment]
`IMPORT` is a NodeBB thing, not a Benchpress / templates.js thing.
