### ISSUE TITLE
Helpers in conditionals inside loops

### ISSUE THREAD

**Issue by vctfernandes** [benchpressjs/benchpressjs#65]
Hey guys,

I have noticed that inside a loop like this:

```
<!-- BEGIN categories -->
  <!-- IF function.myHelper -->
    <p>Hi.</p>
  <!-- ENDIF function.myHelper -->
  {function.myHelper}
<!-- END categories -->
```

{function.myHelper} works accordingly, receiving one single category. However, `<!-- IF function.myHelper -->` receives the entire data object, with all categories, config and all.

Is that expected behavior? How should I be writing loops with conditionals that require helpers?

Thanks!

**Comment by pitaj** [comment]
Conditional helpers get the full data object. If you want a single category, you can pass in the `@index` of the current category like so:

```
<!-- BEGIN categories -->
  <!-- IF function.myHelper, @index -->
    <p>Hi.</p>
  <!-- ENDIF function.myHelper -->
<!-- END categories -->
```

and then your helper function would look like this:

```
function myHelper(data, index) {
  return !!data.categories[index];
}
```

**Comment by pitaj** [comment]
With Benchpress new syntax, use this:

```html
{{{ each categories }}}
  {{{ if function.myHelper, @value }}}
    <p>Hi.</p>
  {{{ end }}}
{{{ end }}}
```
