### ISSUE TITLE
Helpers can only used in loop?

### ISSUE THREAD

**Issue by gogoout** [benchpressjs/benchpressjs#70]
Hi,
I'm reading the code and find this.

in `parseTemplate` `parseFunctions` is called after `parse`
``` js

	function parseTemplate(block, template, obj) {
		block = !block ? template : templates.getBlock(template, block);
		template = parse(block, obj);

		return parseFunctions(template, template, obj);
	}
```

and in the `parse` function
```js
function parse(template, obj, namespace) {
                .....
		namespace = namespace || '';
		if (namespace) {
			namespace = '';
		} else {
			template = checkConditionalHelpers(template, obj);
			template = cleanup(template, obj);
		}

		return template;
	}
```

and the `cleanup` function just remove anything away including helpers.

Then there is no need to call `parseFunctions ` since there is no helpers left. 

Therefore, `parseFunctions` can only be called in the `parseArrayBlock`. Is this a bug or expected?

**Comment by pitaj** [comment]
No longer relevant, consult docs.
