### ISSUE TITLE
Render template client-side

### ISSUE THREAD

**Issue by NicolasSiver** [benchpressjs/benchpressjs#76]
Is it possible? Before 1.9.x it was possible to render templates client-side if you have a template and data.

I'm looking into `Becnhpress.js` and I can not find how I could achieve the same.

You have to use loaders. Does it mean you have to implement templating yourself (`templateFunction`)?

Example: https://github.com/NicolasSiver/nodebb-plugin-ns-points/blob/5e4afdd715e34316f6982c2dcb9cf4414efc5b13/public/js/overview.js#L63

**Comment by pitaj** [comment]
What is the use-case you're looking for? Rendering templates on the client-side is possible, but compiling templates in only available server-side, as the pipeline is very heavy.

**Comment by NicolasSiver** [comment]
I'm into compiling. With `template.js` it was possible to compile the template. 
But as I can see, the compiler is not included in the client-side version of the Benchpress.

Use-case: plugin has only template String, where data and resulting template are computed on client-side only. It's worked before.

**Comment by NicolasSiver** [comment]
I think I'm just looking for the confirmation that client-side compilation is not possible anymore and I'm not missing some approach.

**Comment by pitaj** [comment]
Yep, client-side compilation is not available.

**Comment by NicolasSiver** [comment]
Ok. Thanks.

**Comment by Yehonatan-Albert** [comment]
> Yep, client-side compilation is not available.

Hi pitaj, Is there nothing like #{code...} of pug?
