### ISSUE TITLE
npm i benchpressjs@1.2.7 fails: "can't cd to rust/benchpress-rs"

### ISSUE THREAD

**Issue by RalphORama** [benchpressjs/benchpressjs#81]
Hello,

It appears I'm unable to install benchpressjs.  I first encountered this issue when attempting to upgrade my NodeBB installation, but I've since found that the issue exists even in a brand-new, stand-alone project.

Steps to reproduce: 

1. `mkdir bptest && cd bptest`
2. `npm init -y`
3. `npm i benchpressjs@1.2.7` (I've also tested `npm i benchpressjs`, which produces the same error)

This results in the following error:

```
> benchpressjs@1.2.7 install /root/bptest/node_modules/benchpressjs
> cd rust/benchpress-rs && npm install

sh: 1: cd: can't cd to rust/benchpress-rs
npm WARN bptest@1.0.0 No description
npm WARN bptest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! benchpressjs@1.2.7 install: `cd rust/benchpress-rs && npm install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the benchpressjs@1.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-26T01_06_51_092Z-debug.log
```

[Here are the contents of `2018-11-26T01_06_51_092Z-debug.log`](http://termbin.com/cu9n).

- - -

System information:

- Ubuntu 18.04 LTS 4.15.0-39-generic
- Node v10.13.0
- NPM 6.4.1

**Comment by RalphORama** [comment]
I've also tested the command `npm i benchpressjs`.  Same error.

**Comment by RalphORama** [comment]
I do see several folders when following your instructions:

```
rust:
benchpress-rs

rust/benchpress-rs:
appveyor.yml  benchpress_sys  lib  LICENSE  native  package.json  pre-built  README.md  scripts

rust/benchpress-rs/benchpress_sys:
Cargo.lock  Cargo.toml  src

rust/benchpress-rs/benchpress_sys/src:
bin  generator.rs  instruction.rs  lexer.rs  lib.rs  parser.rs  paths.rs  pre_fixer.rs  templates.rs  token.rs

rust/benchpress-rs/benchpress_sys/src/bin:
bpc.rs

rust/benchpress-rs/lib:
index.js

rust/benchpress-rs/native:
build.rs  Cargo.lock  Cargo.toml  src

rust/benchpress-rs/native/src:
lib.rs

rust/benchpress-rs/pre-built:
do_not_delete  linux_48.node  linux_57.node  linux_59.node  linux_64.node  win32_48.node  win32_57.node  win32_59.node  win32_64.node

rust/benchpress-rs/scripts:
base.appveyor.yml  base.travis.yml  build-configs.js  ci  copy-binary.js  release.js

rust/benchpress-rs/scripts/ci:
add-binary.ps1  add-binary.sh  before.bat  before.sh  push-binaries.ps1  push-binaries.sh
```

I'm not sure what would be causing the "can't cd" error.

**Comment by RalphORama** [comment]
I tried running the installation commands as my normal user account (no `sudo` and not as root), and it works.  I'm not sure what the issue is but it may be something to do with npm rather than bpjs.  I'm still not sure why it wouldn't work as root.

**Comment by pitaj** [comment]
Do you have your `$CDPATH` env var set? According to [this answer on SO](https://stackoverflow.com/a/12487483/847382) it can cause issues.

**Comment by RalphORama** [comment]
`$CDPATH` appears to be unset both for my user and root accounts.  As either user, `echo $CDPATH` doesn't print anything to the console.

**Comment by pitaj** [comment]
What's the output of this command? `npm config ls -l | grep shell`

**Comment by RalphORama** [comment]
As `ralph` and `root` the output is the same:

```
script-shell = null
shell = "/usr/bin/zsh"
```

**Comment by pitaj** [comment]
Hmmm. `zsh`. It should work fine, but can you try `npm config set script-shell bash` and trying again?

To undo that command use `npm config delete script-shell`

**Comment by RalphORama** [comment]
Something must be horribly wrong as root on my machine because after updating the npm config, I get the error 

```
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
```

I'll have a look at what might be causing the issues between my node installation and root.

**Comment by pitaj** [comment]
Ok thanks for trying. I'm gonna close this issue.
