### ISSUE TITLE
Add helpful default globals and helpers

### ISSUE THREAD

**Issue by pitaj** [benchpressjs/benchpressjs#85]
- true
- false
- equal
- or
- and
- greater or equal
- greater than
- less or equal
- less than

**Comment by julianlam** [comment]
While I'm definitely for more complex formulas, I wonder if this is going to affect rendering times :smile: 

I suppose it is less important because the templates are parsed into js/>

**Comment by pitaj** [comment]
If I were to add actual syntax for these, it would be essentially zero overhead.

I'll have to benchmark compare that vs just adding helpers.

**Comment by julianlam** [comment]
Wonderful, thank you for your work on Benchpress :smile:
