### ISSUE TITLE
If statement operators doesn't work properly

### ISSUE THREAD

**Issue by me-cooper** [benchpressjs/benchpressjs#95]
I am using Nodebb v1.16.0 with latest packages and benchpressjs.

I try to use a if statement with operators.
My object looks like this:

```json
"topics": [
        {
            "cid": 14,
            "lastposttime": 1609127989006,
            "mainPid": 143,
            "postcount": 1,
            "slug": "17/relais-beim-ersten-knopfdruck-high-beim-zweiten-knopfdruck-low-setzen",
            "tid": 17,
            "timestamp": 1609127989006,
            "title": "Relais beim ersten Knopfdruck HIGH, beim zweiten Knopfdruck LOW setzen",
            "uid": 1,
            ....
       }
      {
          ...
      }
]
```

Inside of 

```
{{{each topics}}}
```

if try to use

```
{{{ if (category.cid == 14) }}}
   Hello, visitor!
{{{ end }}}
```

But it does not work. `Hello, visitor!` **doesnt show up.**

If I try 

```
{{{ if (category.cid != 100) }}}
   Hello, visitor!
{{{ end }}}
```

It shows up on every topic with cid != 100.

If i try

```
{{{ if (topcis.category.cid == 14) }}}
   Hello, visitor!
{{{ end }}}
```

It also doesnt work.

**Comment by julianlam** [comment]
Odd, have you tried `{{{ if (./topics.cid == 14) }}}`?

**Comment by pitaj** [comment]
Benchpress doesn't have number literals. `14` will text the value from the top-level property `"14"`. Instead try comparing with a string literal: `== 14`. https://github.com/benchpressjs/benchpressjs/blob/master/docs/helpers.md#note-on-numeric-properties

**Comment by me-cooper** [comment]
> Benchpress doesn't have number literals. `14` will text the value from the top-level property `"14"`. Instead try comparing with a string literal: `== 14`. https://github.com/benchpressjs/benchpressjs/blob/master/docs/helpers.md#note-on-numeric-properties

Solved it using

```javascript
{{{ if (topics.category.cid == "14") }}}
   It's cid 14!
{{{ end }}}
```

Thank you for you fast reply!
