### ISSUE TITLE
Give template which gives TreeError

### ISSUE THREAD

**Issue by alfazaz** [benchpressjs/benchpressjs#98]
Hello !

This issue is created after this nodebb community topic : 
https://community.nodebb.org/topic/15235

If we use bad `{{{ if tutu }}} xxxxx {{{ end tutu }}}` in a template, the build raises one or many `Failed at parse::tree::tree, TreeError` without giving the name of the problematic template. It can be long to track these errors with many template files...

[It could also be useful for some people (?) to make `{{{ if tutu }}} xxxxx {{{ end tutu }}}` usable like the `{{{ end }}}` version...]

**Comment by pitaj** [comment]
I've opened #100 to cover allowing `{{{ end tutu }}}` etc

**Comment by alfazaz** [comment]
Ok, thanks !
